// Inquiry field readable map
export const inquiryFieldNameMap = {
    // === Header Fields (ordered) ===
    WF_VBELN: 'InquiryNumber',
    WF_ERDAT: 'RecordCreationDate',
    WF_AUDAT: 'DocumentDate',
    WF_ERNAM: 'CreatedBy',
    WF_KUNNR: 'CustomerNumber',
    WF_VKORG: 'SalesOrganization',
    WF_BSTNK: 'CustomerPONumber',
    WF_ANGDT: 'ValidFrom',
    WF_BNDDT: 'ValidTo',
    WF_WAERK: 'Currency',
  
    WF_VTWEG: 'DistributionChannel',
    WF_SPART: 'Division',
    WF_VKBUR: 'SalesOffice',
    WF_VKGRP: 'SalesGroup',
    WF_AUART: 'InquiryType',
    WF_AUGRU: 'OrderReason',
  
    WF_VTWEG_TXT: 'DistributionChannelText',
    WF_SPART_TXT: 'DivisionText',
    WF_VKBUR_TXT: 'SalesOfficeText',
    WF_VKGRP_TXT: 'SalesGroupText',
    WF_VKORG_TXT: 'SalesOrganizationText',
    WG_FULLY_ORDERED: 'FullyOrderedFlag',
    WG_PARTIALLY_ORDERED: 'PartiallyOrderedFlag',
    WF_STATUS_TEXT: 'Status',
    WF_TOTAL_ITEMS: 'TotalItems',
    WF_TOTAL_NETWR: 'TotalNetValue',
    WF_ORDERED_ITEMS: 'TotalOrderedItems',

    // === Item Fields (ordered) ===
    WF_VBELN: 'InquiryNumber',
    WF_POSNR: 'ItemNumber',
    WF_MATNR: 'MaterialNumber',
    WF_ARKTX: 'Description',
    WF_KWMENG: 'Quantity',
    WF_VRKME: 'SalesUnit',
    WF_NETPR: 'NetPrice',
    WF_NETWR: 'NetValue',
    WF_WAERK: 'Currency',
    WG_IS_ORDERED: 'IsOrderedFlag',
    WF_VBELN_SO: 'SalesOrderNumber',
    WF_POSNR_SO: 'SalesOrderItemNumber'
  };

  
// Sales Orders field readable map
export const salesOrderFieldNameMap = {
    WF_VBELN: 'SalesOrderNumber',
    WF_ERDAT: 'RecordCreationDate',
    WF_AUDAT: 'DocumentDate',
    WF_ERNAM: 'CreatedBy',
    WF_KUNNR: 'CustomerNumber',
    WF_VKORG: 'SalesOrganization',
    WF_VTWEG: 'DistributionChannel',
    WF_SPART: 'Division',
    WF_VKBUR: 'SalesOffice',
    WF_VKGRP: 'SalesGroup',
    WF_BSTNK: 'CustomerPONumber',
    WF_WAERK: 'Currency',
    WF_AUART: 'SalesOrderType',
    WF_VBTYP: 'DocumentCategory',
    WF_VDATU: 'RequestedDeliveryDate',
    WF_NETWR: 'NetValue',
    WF_FKSTK: 'BillingStatus',
    WF_VTWEG_TXT: 'DistributionChannelText',
    WF_SPART_TXT: 'DivisionText',
    WF_VKBUR_TXT: 'SalesOfficeText',
    WF_VKGRP_TXT: 'SalesGroupText',
    WF_VKORG_TXT: 'SalesOrganizationText',

    WF_TOTAL_ITEMS: 'TotalItems',
    WF_TOTAL_NETWR: 'TotalNetValue',
    WF_DELIVERED_ITEMS: 'DeliveredItems',
    WF_STATUS_TEXT: 'DeliveryStatus',
    WG_FULLY_DELIVERED: 'IsFullyDelivered',
    WG_PARTIALLY_DELIVERED: 'IsPartiallyDelivered',

    // Item level fields
    WF_POSNR: 'ItemNumber',
    WF_MATNR: 'MaterialNumber',
    WF_ARKTX: 'Description',
    WF_KWMENG: 'Quantity',
    WF_VRKME: 'Unit',
    WF_PSTYV: 'ItemCategory',
    WF_NETPR: 'ItemUnitValue',
    WF_NETWR_ITEM: 'ItemNetValue',
    WF_WAERK_ITEM: 'ItemCurrency',
    WG_IS_DELIVERED: 'IsDelivered',
    WF_VBELN_DEL: 'DeliveryNumber',
    WF_POSNR_DEL: 'DeliveryItemNumber'
};

// Deliveries field readable map
export const deliveryFieldNameMap = {
  // Header level fields
  WF_VBELN: 'DeliveryNumber',
  WF_LFDAT: 'PlannedGoodsIssueDate',
  WF_WADAT: 'ActualGoodsIssueDate',
  WF_ERDAT: 'RecordCreationDate',
  WF_VSTEL: 'ShippingPoint',
  WF_VKORG: 'SalesOrganization',
  WF_VKGRP: 'SalesGroup',
  WF_VTWIV: 'DistributionChannel',
  WF_LFART: 'DeliveryType',
  WF_KUNAG: 'ShipToParty',
  WF_KUNNR: 'SoldToParty',
  WF_FKDAT: 'BillingDate',
  WF_LDDAT: 'LoadingDate',
  WF_TDDAT: 'TransportationPlanningDate',
  WF_VSBED: 'ShippingCondition',
  WF_ROUTE: 'Route',
  WF_FAKSK: 'BillingBlock',
  WF_VKBUR: 'SalesOffice',
  WF_WAERK: 'Currency',
  WF_BUKRS: '',

  // Header text descriptions
  WF_VSTEL_TXT: 'ShippingPointText',
  WF_VKORG_TXT: 'SalesOrganizationText',
  WF_VTWIV_TXT: 'DistributionChannelText',
  WF_LFART_TXT: 'DeliveryTypeText',
  WF_VSBED_TXT: 'ShippingConditionText',
  WF_FAKSK_TXT: 'BillingBlockText',
  WF_VKBUR_TXT: 'SalesOfficeText',
  WF_ROUTE_TXT: "RouteText",

  // Header computed fields
  WF_TOTAL_ITEMS: 'TotalItems',
  WF_TOTAL_NETWR: 'TotalNetValue',
  WF_BILLED_ITEMS: 'BilledItems',
  WF_PICKED_ITEMS: 'PickedItems',
  WF_PACKED_ITEMS: 'PackedItems',
  WF_STATUS_TEXT: 'DeliveryBillingStatusText',
  WG_FULLY_BILLED: 'IsFullyBilled',
  WG_PARTIALLY_BILLED: 'IsPartiallyBilled',
  WG_FULLY_PICKED: 'IsFullyPacked',
  WG_FULLY_PACKED: 'IsFullyPacked',

  // Item level fields
  WF_POSNR: 'ItemNumber',
  WF_MATNR: 'MaterialNumber',
  WF_ARKTX: 'MaterialDescription',
  WF_LFIMG: 'DeliveryQuantity',
  WF_MEINS: 'UOM',
  WF_NETWR: 'NetValue',
  WF_NAME2: 'PlantName',
  WF_STRAS: 'Street',
  WF_PSTLZ: 'PostalCode',
  WF_ORT01: 'City',
  WF_LGOBE: 'StorageLocationText',
  WF_WERKS: 'Plant',
  WF_VGBEL: 'ReferenceDocument',
  WF_VGPOS: 'ReferenceItem',
  WF_CHARG: 'BatchNumber',
  WF_LGMNG: 'PickedQuantity',
  WG_IS_BILLED: 'IsBilled',
  WF_VBELN_BILL: 'BillingDocument',
  WF_POSNR_BILL: 'BillingItem',
  WG_PICKED: 'PickingStatus',
  WG_PACKED: 'PackingStatus',
  WF_GI_STATUS: 'GoodsIssueStatus'
};
